routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/

Route::resource('field', 'FieldController');
Route::get('field/destroy/{id}', ['as'=> 'field/destroy', 'uses' => 'FieldController@destroy']);
Route::post('field/show', ['as' => 'field/show', 'uses' => 'FieldController@show']);
Route::post('field/update/{id}', ['as' => 'field/update','uses' => 'FieldController@update']);

Route::resource('rental', 'RentalController');
Route::get('rental/destroy/{id}', ['as'=> 'rental/destroy', 'uses' => 'RentalController@destroy']);
Route::post('rental/show', ['as' => 'rental/show', 'uses' => 'RentalController@show']);
Route::post('rental/update/{id}', ['as' => 'rental/update','uses' => 'RentalController@update']);

Route::resource('reserva', 'ReservaController');
Route::get('reserva/destroy/{id}', ['as'=> 'reserva/destroy', 'uses' => 'reservaController@destroy']);
Route::post('reserva/show', ['as' => 'reserva/show', 'uses' => 'ReservaController@show']);
Route::post('reserva/update/{id}', ['as' => 'reserva/update','uses' => 'ReservaController@update']);

Route::resource('perfil', 'PerfilController');
Route::post('perfil/show', ['as' => 'perfil/show', 'uses' => 'PerfilController@show']);
Route::post('perfil/update/{id}', ['as' => 'perfil/update', 'uses' => 'PerfilController@update']);

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Field.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Field extends Model
{
    protected $table = 'fields';
    protected $fillable = ['status_id','name','foto'];
    protected $guarded = ['id'];

    public function rentals()
    {
    	return $this->hasMany('App\Models\Rental');
    }

    public function status()
    {
    	return $this->belongsTo('App\Models\Status');
    }
}

app/Http/Controllers/FieldController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Field as Field;
use App\Models\Status;

class FieldController extends Controller
{
    public function index()
    {
        $fields = Field::all();
        $statuses = Status::where('type_status_id',1)->get();
        return \View::make('fields/list',compact('fields','statuses'));
    }

    public function create()
    {   
        $statuses = Status::where('type_status_id',1)->get();
        return \View::make('fields/new',compact('statuses'));
    }
    
    public function edit($id)
    {
        $field = Field::find($id);
        $statuses = Status::where('type_status_id', 1)->get();
        return \View::make('fields/update',compact('field','statuses'));
    }
    public function update($id, Request $request)
    {
        $field = Field::find($id);
        $field->status_id = $request->status_id;
        $field->name = $request->name;
        $fileName               = $request->name.'.'.$request->file('foto')->extension();
            $path                   = '/public/images/';
            $storePath              = '/storage/images/';
            $field->foto = $storePath.$fileName;
            $request->file('foto')->storeAs($path, $fileName);
        $field->save();
        return redirect(\Auth::user()->urlFieldAll());
    }

    public function show(Request $request)
    {
        $fields = Field::where('name','like','%'.$request->name.'%')->get();
        $statuses = Status::where('type_status_id', 1)->get();
        return \View::make('fields/list',compact('fields','statuses'));
    }

    public function destroy($id)
    {
        $field = Field::find($id);
        $field->delete();
        return redirect()->back();
    }

    public function store(Request $request)
    {

        $field = new Field;
        $field->status_id = $request->status_id;
        $field->name = $request->name;
        $fileName               = $request->name.'.'.$request->file('foto')->extension();
            $path                   = '/public/images/';
            $storePath              = '/storage/images/';
            $field->foto = $storePath.$fileName;
            $request->file('foto')->storeAs($path, $fileName);
        $field->save();
        return redirect(\Auth::user()->urlFieldAll());
    }

}

resources/views/fields/list.blade.php
@extends('layouts.argon')
@section('content')
<script>

        (function() {
          'use strict';
          window.addEventListener('load', function() {
            
            var forms = document.getElementsByClassName('needs-validation');
            var validation = Array.prototype.filter.call(forms, function(form) {
              form.addEventListener('submit', function(event) {
                if (form.checkValidity() === false) {
                  event.preventDefault();
                  event.stopPropagation();
                }
                form.classList.add('was-validated');
              }, false);
            });
          }, false);
        })();
</script>
	<div class="main-content" id="panel">
    <div class="header  pb-6">
      <div class="container-fluid">
        <div class="header-body">
          <div class="row align-items-center py-4">
            <div class="col-lg-6 col-7">
              <h6 class="h2 text-blck d-inline-block mb-0">Canchas</h6>
              <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                  <li class="breadcrumb-item"><a href="{{route('home')}}"><i class="fas fa-home"></i></a></li>
                  <li class="breadcrumb-item"><a href="#">Listado</a></li>
                  <li class="breadcrumb-item active" aria-current="page">Gestión</li>
                </ol>
              </nav>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="container-fluid mt--6">
      <div class="row">
        <div class="col">
          <div class="card">
            <!-- Card header -->
            <div class="card-header border-0">
              <div>
                <!--<h2 class="mb-0">Gestion Usuarios</h3>-->
              </div><br>
              <form action="{{ url( Auth::user()->urlFieldShow() ) }}" method="post" novalidate class="form-inline">
                   @csrf
                    <div class="form-group">
                        <label class="mr-2">Nombre </label>
                        <input type="text" name="name" class="form-control" placeholder="Buscar por Nombre">
                    </div>
                    <div class="form-group">
                       	<button type="submit" class="btn btn-info ml-2 mr-2">Buscar</button>
                        <a href="{{ url( Auth::user()->urlFieldAll()) }}" class="btn btn-warning">Todo</a>
                        @if( Auth::user()->role->name != 'Cliente')
                          <a href="{{ url( Auth::user()->urlFieldCreate() ) }}" class="btn btn-success" data-toggle="modal" data-target="#crear">Crear</a>
                        @endif
                    </div>
               </form>
            </div>
            <!-- Light table -->
            <div class="table-responsive">
              <table class="table align-items-center table-flush">
                <thead class="thead-light">
                  <tr>
                    <th scope="col" class="sort" data-sort="name">#</th>
                    <th scope="col" class="sort" data-sort="budget">Nombre</th>
                    <th scope="col" class="sort" data-sort="budget">foto</th>
                    <th scope="col" class="sort" data-sort="status">Estado</th>
                    <th scope="col" class="sort" data-sort="status">Acción</th>
                  </tr>
                </thead>
                <tbody class="list">
                  @foreach($fields as $field)
						<tr>
							<td>{{$field->id}}</td>
							<td>{{$field->name}}</td>
              <td>
                <img class="foto" src="{{asset($field->foto)}}" > 
              </td>
							<td>{{$field->status->name}}</td>
							<td>
                @if( Auth::user()->role->name != 'Cliente')
								  <a class="btn btn-success btn-xs" 
								  href="{{url( Auth::user()->urlFieldEdit($field->id) ) }}">
								    <i class="ni ni-ruler-pencil "></i>
								  </a>
							   <a class="btn btn-danger btn-xs" href="{{url(Auth::user()->urlFieldDestroy($field->id))}}">Eliminar</a>
                @endif
							</td>
						</tr>
				  @endforeach
                </tbody>
              </table>
            </div>
            <!-- Card footer -->
            <div class="card-footer py-4">
              <nav aria-label="...">
                <ul class="pagination justify-content-end mb-0">
                  <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1">
                      <i class="fas fa-angle-left"></i>
                      <span class="sr-only">Previous</span>
                    </a>
                  </li>
                  <li class="page-item active">
                    <a class="page-link" href="#">1</a>
                  </li>
                  <li class="page-item">
                    <a class="page-link" href="#">2 <span class="sr-only">(current)</span></a>
                  </li>
                  <li class="page-item"><a class="page-link" href="#">3</a></li>
                  <li class="page-item">
                    <a class="page-link" href="#">
                      <i class="fas fa-angle-right"></i>
                      <span class="sr-only">Next</span>
                    </a>
                  </li>
                </ul>
              </nav>
            </div>
          </div>
          <div class="modal fade" id="crear" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-lg">
                <div class="modal-content">
                  <div class="modal-header bg-success">
                    <h5 class="modal-title text-white" >Crear Cancha</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                  	<form action="{{ url( Auth::user()->urlFieldAll())}}" method="post" class="needs-validation" novalidate accept-charset="UTF-8" enctype="multipart/form-data">
		                @csrf

    		            		<div class="form-group ">
    		            			<label class="col-form-label ">Nombre</label>
    		                  <input  type="text" name="name" class="form-control " id="validationCustom01" required>
                          <div class="valid-feedback">
                                Correcto!
                            </div>
                            <div class="invalid-feedback">
                                Complete el recuadro
                          </div>
    		            		</div>
                        <div class="form-group ">
                          <label class="col-form-label ">Foto</label>
                          <input  type="file" name="foto" class="form-control " id="validationCustom01" required>
                          <div class="valid-feedback">
                                Correcto!
                          </div>
                          <div class="invalid-feedback">
                                Complete el recuadro
                          </div>
                        </div>
                        <div class="form-group ">
                        <label class=" col-form-label ">estado</label>
                        <select name="status_id" class="form-control" required>
                        <option value="">Seleccione...</option>
                        @foreach($statuses as $status)
                          <option value="{{$status->id}}">{{$status->name}}</option>
                        @endforeach
                        </select>
                        <div class="valid-feedback">
                            Correcto!
                          </div>
                          <div class="invalid-feedback">
                            Complete el recuadro
                          </div>
                      </div>
		            		

		            		<div class="form-group ">
		            			<button type="submit" class="btn btn-success float-right">Registrar</button>
		                    </div>
		            </form>
                  </div>
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/fields/new.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
        		<div class="card border-success">
          			<div class="card-header bg-success ">
            			Crear Cancha
          			</div>
          			<div class="card-body ">
            			<form action="{{route('field.store')}}" method="post">
                            @csrf

                            <div class="form-group ">
                                <label class="col-form-label ">Estado</label>
                                <input  type="text" name="status_id" class="form-control ">
                            </div>
            				<div class="form-group ">
            					<label class="col-form-label ">Nombre</label>
                                <input  type="text" name="name" class="form-control ">
            				</div>
            		

            				<div class="form-group ">
            				    <button type="submit" class="btn btn-success full-width">Registrar</button>
                            </div>
            			</form>
          			</div>
        		</div>
            </div>
        </div>
	</section>
@endsection

resources/views/fields/update.blade.php
@extends('layouts.argon')
@section('content')
    <section class="main-content" id="panel">
        <div class="header  pb-6">
            <div class="container-fluid ">
                <div class="header-body " >
                    <div class="row align-items-right py-4">
                        <div class="col-lg-6 col-7">
                          <h6 class="h2 text-blck d-inline-block ">Canchas</h6>
                          <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4  ">
                            <ol class="breadcrumb breadcrumb-links breadcrumb-dark ">
                              <li class="breadcrumb-item "><a href="{{route('home')}}"><i class="fas fa-home"></i></a></li>
                              <li class="breadcrumb-item "><a href="#">Listado</a></li>
                              <li class="breadcrumb-item active " aria-current="page">Editar</li>
                            </ol>
                          </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="container-fluid mt--6 ">
            <div class="row">
                <div class="col-md-12 mt-3">
                    <div class="card  border-success">
                        <div class="card-header bg-success  text-white ">
                            Información Cancha
                        </div>
                        <div class="card-body ">
                            <form action="{{url( \Auth::user()->urlFieldUpdate($field->id) ) }}" method="post" accept-charset="UTF-8" enctype="multipart/form-data">
                                @csrf

                                <div class="form-group ">
                                    <label >Estado</label>
                                    <select name="status_id" class="form-control" required>
                                        
                                        <option value="">Seleccione...</option>
                                        @foreach($statuses as $status)
                                            @if($status->id == $field->status_id)
                                                <option value="{{$status->id}}" selected>{{$status->name}}</option>
                                            @else
                                                <option value="{{$status->id}}">{{$status->name}}</option>
                                            @endif
                                        @endforeach
                                    </select>
                                </div>
                                <div class="form-group ">
                                    <label>Nombre</label>
                                    <input  type="text" name="name" class="form-control " value="{{$field->name}}">
                                </div>
                                <div class="form-group ">
                                    <label class="col-form-label ">Foto</label>
                                    <input  type="file" name="foto" class="form-control" value="{$field-foto}">
                                </div>
                                <div class="form-group ">
                                    <button type="submit" class="btn btn-success float-right">Guardar</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection